ALTER TYPE "SubscriptionPlanType" ADD VALUE IF NOT EXISTS 'GROWTH';
ALTER TABLE "SubscriptionPlan" ADD COLUMN "maxAiRequests" INTEGER NOT NULL DEFAULT 0, ADD COLUMN "stripePriceId" TEXT;
CREATE UNIQUE INDEX "SubscriptionPlan_stripePriceId_key" ON "SubscriptionPlan"("stripePriceId");

CREATE TYPE "BillingSubscriptionStatus" AS ENUM ('ACTIVE','TRIALING','PAST_DUE','CANCELED','UNPAID','INCOMPLETE');
CREATE TYPE "BillingInvoiceStatus" AS ENUM ('DRAFT','OPEN','PAID','VOID','UNCOLLECTIBLE','FAILED');
CREATE TYPE "UsageMetricType" AS ENUM ('CONVERSATIONS','MESSAGES','AI_REQUESTS','AI_TOKENS','KB_DOCUMENTS','KB_STORAGE_BYTES','AGENTS');
CREATE TYPE "UsageAlertThreshold" AS ENUM ('EIGHTY','NINETY_FIVE','ONE_HUNDRED');

CREATE TABLE "BillingCustomer" ("id" TEXT NOT NULL, "companyId" TEXT NOT NULL, "stripeCustomerId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "BillingCustomer_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "BillingCustomer_companyId_key" ON "BillingCustomer"("companyId"); CREATE UNIQUE INDEX "BillingCustomer_stripeCustomerId_key" ON "BillingCustomer"("stripeCustomerId"); ALTER TABLE "BillingCustomer" ADD CONSTRAINT "BillingCustomer_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "BillingSubscription" ("id" TEXT NOT NULL, "companyId" TEXT NOT NULL, "stripeSubscriptionId" TEXT NOT NULL, "stripePriceId" TEXT NOT NULL, "status" "BillingSubscriptionStatus" NOT NULL, "currentPeriodStart" TIMESTAMP(3) NOT NULL, "currentPeriodEnd" TIMESTAMP(3) NOT NULL, "cancelAtPeriodEnd" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "BillingSubscription_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "BillingSubscription_companyId_key" ON "BillingSubscription"("companyId"); CREATE UNIQUE INDEX "BillingSubscription_stripeSubscriptionId_key" ON "BillingSubscription"("stripeSubscriptionId"); ALTER TABLE "BillingSubscription" ADD CONSTRAINT "BillingSubscription_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "BillingInvoice" ("id" TEXT NOT NULL, "companyId" TEXT NOT NULL, "stripeInvoiceId" TEXT NOT NULL, "stripeCustomerId" TEXT, "status" "BillingInvoiceStatus" NOT NULL, "amountDue" INTEGER NOT NULL, "amountPaid" INTEGER NOT NULL DEFAULT 0, "currency" TEXT NOT NULL DEFAULT 'usd', "hostedInvoiceUrl" TEXT, "invoicePdf" TEXT, "periodStart" TIMESTAMP(3), "periodEnd" TIMESTAMP(3), "paidAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "BillingInvoice_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "BillingInvoice_stripeInvoiceId_key" ON "BillingInvoice"("stripeInvoiceId"); CREATE INDEX "BillingInvoice_companyId_createdAt_idx" ON "BillingInvoice"("companyId","createdAt"); ALTER TABLE "BillingInvoice" ADD CONSTRAINT "BillingInvoice_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "BillingEvent" ("id" TEXT NOT NULL, "companyId" TEXT, "stripeEventId" TEXT NOT NULL, "type" TEXT NOT NULL, "payload" JSONB NOT NULL, "processedAt" TIMESTAMP(3), "failedAt" TIMESTAMP(3), "failureReason" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "BillingEvent_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "BillingEvent_stripeEventId_key" ON "BillingEvent"("stripeEventId"); CREATE INDEX "BillingEvent_companyId_createdAt_idx" ON "BillingEvent"("companyId","createdAt"); ALTER TABLE "BillingEvent" ADD CONSTRAINT "BillingEvent_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE SET NULL ON UPDATE CASCADE;
CREATE TABLE "UsageMetric" ("id" TEXT NOT NULL, "companyId" TEXT NOT NULL, "metricType" "UsageMetricType" NOT NULL, "quantity" INTEGER NOT NULL, "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "metadata" JSONB, CONSTRAINT "UsageMetric_pkey" PRIMARY KEY ("id")); CREATE INDEX "UsageMetric_companyId_metricType_timestamp_idx" ON "UsageMetric"("companyId","metricType","timestamp"); ALTER TABLE "UsageMetric" ADD CONSTRAINT "UsageMetric_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "AIUsageCost" ("id" TEXT NOT NULL, "companyId" TEXT NOT NULL, "provider" TEXT NOT NULL, "model" TEXT NOT NULL, "inputTokens" INTEGER NOT NULL DEFAULT 0, "outputTokens" INTEGER NOT NULL DEFAULT 0, "totalTokens" INTEGER NOT NULL, "estimatedCost" DOUBLE PRECISION NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AIUsageCost_pkey" PRIMARY KEY ("id")); CREATE INDEX "AIUsageCost_companyId_createdAt_idx" ON "AIUsageCost"("companyId","createdAt"); ALTER TABLE "AIUsageCost" ADD CONSTRAINT "AIUsageCost_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "UsageAlert" ("id" TEXT NOT NULL, "companyId" TEXT NOT NULL, "metricType" "UsageMetricType" NOT NULL, "threshold" "UsageAlertThreshold" NOT NULL, "percentage" INTEGER NOT NULL, "limit" INTEGER NOT NULL, "quantity" INTEGER NOT NULL, "periodStart" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "UsageAlert_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "UsageAlert_companyId_metricType_threshold_periodStart_key" ON "UsageAlert"("companyId","metricType","threshold","periodStart"); CREATE INDEX "UsageAlert_companyId_createdAt_idx" ON "UsageAlert"("companyId","createdAt"); ALTER TABLE "UsageAlert" ADD CONSTRAINT "UsageAlert_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
