import type { Message } from '@prisma/client'

/**
 * Configuration for AI operations
 */
export interface AIConfig {
  provider: 'openai' | 'mock'
  apiKey?: string
  model: string
  maxTokens: number
  temperature: number
  contextWindowTokens: number
  confidenceThreshold: number
  handoffOnLowConfidence: boolean
  handoffOnUnsupportedTopic: boolean
  streamTimeout: number // milliseconds
}

/**
 * Context for AI operations
 */
export interface ConversationContext {
  conversationId: string
  customerId: string
  agentId?: string
  messages: Message[]
  summary?: string
  metadata?: Record<string, unknown>
  recentMessageCount: number
}

/**
 * Streaming response chunk
 */
export interface StreamingChunk {
  content: string
  finishReason?: string
  tokenCount?: number
}

/**
 * AI response with confidence score
 */
export interface AIResponse {
  content: string
  confidence: number
  shouldHandoff: boolean
  handoffReason?: string
  tokenUsage: {
    prompt: number
    completion: number
    total: number
  }
  generatedAt: Date
}

/**
 * Suggestions generated by AI
 */
export interface AISuggestions {
  suggestions: string[]
  confidence: number
  topic?: string
  generatedAt: Date
}

/**
 * Conversation summary
 */
export interface ConversationSummary {
  summary: string
  keyPoints: string[]
  sentiment?: string
  resolution?: string
  generatedAt: Date
}

/**
 * Topics that require human agent
 */
export interface UnsupportedTopic {
  keyword: string
  handoffRequired: boolean
}
