export const SocketEvents = {
  ROOM_JOIN: 'room:join',
  ROOM_LEAVE: 'room:leave',
  TYPING: 'typing',
  MESSAGE_CREATE: 'message:create',
  MESSAGE_CREATED: 'message:created',
  MESSAGE_UPDATED: 'message:updated',
  MESSAGE_DELIVERED: 'message:delivered',
  MESSAGE_READ: 'message:read',
  CONVERSATION_READ: 'conversation:read',
  CONVERSATION_ASSIGN: 'conversation:assign',
  CONVERSATION_ASSIGNED: 'conversation:assigned',
  CONVERSATION_TRANSFER: 'conversation:transfer',
  CONVERSATION_TRANSFERRED: 'conversation:transferred',
  CONVERSATION_ESCALATED: 'conversation:escalated',
  CONVERSATION_RESOLVED: 'conversation:resolved',
  CONVERSATION_CLOSED: 'conversation:closed',
  CONVERSATION_REOPENED: 'conversation:reopened',
  CONVERSATION_UPDATED: 'conversation:updated',
  AGENT_JOIN: 'agent:join',
  AGENT_JOINED: 'agent:joined',
}
