import crypto from 'crypto'
import { generateSecret, generateURI, verify } from 'otplib'
import { SAML } from '@node-saml/node-saml'
import { prisma } from '../../config/prisma'
import TokenService from '../auth/token.service'
import { auditLogService } from '../audit/audit.service'

type Provider = 'OKTA' | 'AZURE_AD' | 'GOOGLE_WORKSPACE'
type PolicyInput = { minPasswordLength?: number; requireUppercase?: boolean; requireLowercase?: boolean; requireNumber?: boolean; requireSymbol?: boolean; sessionTimeoutMinutes?: number; allowedEmailDomains?: string[]; ipAllowlist?: string[] }

const encryptionKey = () => crypto.createHash('sha256').update(process.env.MFA_ENCRYPTION_KEY || process.env.JWT_SECRET || 'invalid').digest()
function encrypt(value: string): string { const iv = crypto.randomBytes(12); const cipher = crypto.createCipheriv('aes-256-gcm', encryptionKey(), iv); const encrypted = Buffer.concat([cipher.update(value, 'utf8'), cipher.final()]); return `${iv.toString('base64')}.${cipher.getAuthTag().toString('base64')}.${encrypted.toString('base64')}` }
function decrypt(value: string): string { const [iv, tag, encrypted] = value.split('.'); const decipher = crypto.createDecipheriv('aes-256-gcm', encryptionKey(), Buffer.from(iv, 'base64')); decipher.setAuthTag(Buffer.from(tag, 'base64')); return Buffer.concat([decipher.update(Buffer.from(encrypted, 'base64')), decipher.final()]).toString('utf8') }
const hash = (value: string) => crypto.createHash('sha256').update(value).digest('hex')

export class IdentityService {
  async getPolicy(companyId: string) { return (prisma as any).companySecurityPolicy.upsert({ where: { companyId }, update: {}, create: { companyId, allowedEmailDomains: [], ipAllowlist: [] } }) }
  async updatePolicy(companyId: string, input: PolicyInput, actorId?: string) { const policy = await (prisma as any).companySecurityPolicy.upsert({ where: { companyId }, update: input, create: { companyId, allowedEmailDomains: [], ipAllowlist: [], ...input } }); await auditLogService.log(companyId, 'SECURITY_POLICY_CHANGED' as any, 'security_policy', policy.id, actorId, input); return policy }
  async enforcePolicy(companyId: string, ip?: string) { const policy = await (prisma as any).companySecurityPolicy.findUnique({ where: { companyId } }); if (policy?.ipAllowlist?.length && (!ip || !policy.ipAllowlist.includes(ip))) throw new Error('IP address is not allowed') }
  async validateCredentials(companyId: string, email?: string, password?: string) { const policy = await this.getPolicy(companyId); if (email && policy.allowedEmailDomains.length && !policy.allowedEmailDomains.some((domain: string) => email.toLowerCase().endsWith(`@${domain.toLowerCase()}`))) throw new Error('Email domain is not allowed'); if (password && (password.length < policy.minPasswordLength || (policy.requireUppercase && !/[A-Z]/.test(password)) || (policy.requireLowercase && !/[a-z]/.test(password)) || (policy.requireNumber && !/[0-9]/.test(password)) || (policy.requireSymbol && !/[^A-Za-z0-9]/.test(password)))) throw new Error('Password does not meet company policy') }
  async beginMfa(userId: string) { const secret = generateSecret(); const recoveryCodes = Array.from({ length: 10 }, () => crypto.randomBytes(8).toString('hex')); await (prisma as any).user.update({ where: { id: userId }, data: { mfaSecret: encrypt(secret), recoveryCodes: recoveryCodes.map(hash), mfaEnabled: false } }); return { secret, otpAuthUri: generateURI({ issuer: 'Chatbot App', label: userId, secret }), recoveryCodes } }
  async enableMfa(userId: string, token: string) { const user = await (prisma as any).user.findUnique({ where: { id: userId } }); if (!user?.mfaSecret || !(await verify({ secret: decrypt(user.mfaSecret), token, epochTolerance: 1 }))) throw new Error('Invalid MFA code'); return (prisma as any).user.update({ where: { id: userId }, data: { mfaEnabled: true }, select: { id: true, mfaEnabled: true } }) }
  async verifyMfa(userId: string, token: string) { const user = await (prisma as any).user.findUnique({ where: { id: userId } }); if (!user?.mfaEnabled || !user.mfaSecret) return true; if (await verify({ secret: decrypt(user.mfaSecret), token, epochTolerance: 1 })) return true; const codes = Array.isArray(user.recoveryCodes) ? user.recoveryCodes as string[] : []; const tokenHash = hash(token); const index = codes.findIndex((code) => crypto.timingSafeEqual(Buffer.from(code), Buffer.from(tokenHash))); if (index < 0) return false; codes.splice(index, 1); await (prisma as any).user.update({ where: { id: userId }, data: { recoveryCodes: codes } }); return true }
  async disableMfa(userId: string, token: string) { if (!(await this.verifyMfa(userId, token))) throw new Error('Invalid MFA code'); return (prisma as any).user.update({ where: { id: userId }, data: { mfaEnabled: false, mfaSecret: null, recoveryCodes: null }, select: { id: true, mfaEnabled: true } }) }
  async sessions(userId: string) { return (prisma as any).refreshToken.findMany({ where: { userId, isRevoked: false, expiresAt: { gt: new Date() } }, orderBy: { createdAt: 'desc' }, select: { id: true, deviceId: true, deviceName: true, ipAddress: true, userAgent: true, createdAt: true, lastUsedAt: true, expiresAt: true } }) }
  async companySessions(companyId: string) { return (prisma as any).refreshToken.findMany({ where: { user: { companyId }, isRevoked: false, expiresAt: { gt: new Date() } }, orderBy: { createdAt: 'desc' }, select: { id: true, userId: true, deviceId: true, deviceName: true, ipAddress: true, userAgent: true, createdAt: true, lastUsedAt: true, expiresAt: true } }) }
  async revokeSession(userId: string, sessionId: string) { const session = await (prisma as any).refreshToken.findFirst({ where: { id: sessionId, userId } }); if (!session) throw new Error('Session not found'); return (prisma as any).refreshToken.update({ where: { id: sessionId }, data: { isRevoked: true, revokedAt: new Date() } }) }
  async revokeAllSessions(userId: string) { return (prisma as any).refreshToken.updateMany({ where: { userId, isRevoked: false }, data: { isRevoked: true, revokedAt: new Date() } }) }
  async revokeAllCompanyUserSessions(companyId: string, userId: string) { const user = await (prisma as any).user.findFirst({ where: { id: userId, companyId } }); if (!user) throw new Error('User not found'); return this.revokeAllSessions(userId) }
  async configureSso(companyId: string, provider: Provider, input: { entityId: string; ssoUrl: string; certificate: string }, actorId?: string) { const result = await (prisma as any).ssoConnection.upsert({ where: { companyId_provider: { companyId, provider } }, update: input, create: { companyId, provider, ...input } }); await auditLogService.log(companyId, 'SSO_CONFIGURED' as any, 'sso_connection', result.id, actorId, { provider }); return result }
  async createScimToken(companyId: string, actorId?: string) { const raw = `scim_${crypto.randomBytes(32).toString('hex')}`; const record = await (prisma as any).scimToken.create({ data: { companyId, tokenHash: hash(raw) } }); await auditLogService.log(companyId, 'SCIM_TOKEN_CREATED' as any, 'scim_token', record.id, actorId); return { id: record.id, token: raw, createdAt: record.createdAt } }
  async ssoLogin(companyId: string, provider: Provider, callbackUrl: string) { const config = await (prisma as any).ssoConnection.findFirst({ where: { companyId, provider, enabled: true } }); if (!config) throw new Error('SSO provider is not configured'); const saml = new SAML({ callbackUrl, entryPoint: config.ssoUrl, issuer: config.entityId, idpCert: config.certificate, wantAssertionsSigned: true, wantAuthnResponseSigned: true }); return saml.getAuthorizeUrlAsync('', callbackUrl, {}) }
  async ssoCallback(companyId: string, provider: Provider, callbackUrl: string, body: Record<string, string>) { const config = await (prisma as any).ssoConnection.findFirst({ where: { companyId, provider, enabled: true } }); if (!config) throw new Error('SSO provider is not configured'); const saml = new SAML({ callbackUrl, entryPoint: config.ssoUrl, issuer: config.entityId, idpCert: config.certificate, wantAssertionsSigned: true, wantAuthnResponseSigned: true }); const result = await saml.validatePostResponseAsync(body); const email = String(result.profile?.email || result.profile?.['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress'] || '').toLowerCase(); if (!email) throw new Error('SAML assertion has no email'); const user = await (prisma as any).user.findFirst({ where: { companyId, email, isActive: true } }); if (!user) throw new Error('SSO user is not provisioned'); return { token: TokenService.sign({ userId: user.id, role: user.role, companyId }) } }
}
export const identityService = new IdentityService()
