export const ROUTES = {
  home: '/',
  customerLogin: '/customer/login',
  customerRegister: '/customer/register',
  customerDashboard: '/customer',
  customerConversations: '/customer/conversations',
  customerConversationDetail: '/customer/conversations/:conversationId',
  agentLogin: '/agent/login',
  agentDashboard: '/agent',
  agentConversations: '/agent/conversations',
  agentConversationDetail: '/agent/conversations/:conversationId',
  adminLogin: '/admin/login',
  adminDashboard: '/admin',
  adminConversations: '/admin/conversations',
  settingsCompany: '/settings/company',
  settingsUsers: '/settings/users',
  settingsAi: '/settings/ai',
  settingsKnowledge: '/settings/knowledge',
  settingsBilling: '/settings/billing',
  settingsAnalytics: '/settings/analytics',
  settingsWebhooks: '/settings/webhooks',
  settingsEmail: '/settings/channels/email',
  settingsApiKeys: '/settings/api-keys',
  profile: '/profile',
  unauthorized: '/unauthorized',
  notFound: '*',
}
